# Generated by Django 3.2.4 on 2024-08-01 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flan_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image_url', models.URLField(default='https://example.com/default-image.jpg')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
    ]
