# Generated by Django 3.2.4 on 2024-08-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='UsuarioForm',
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Formulario de Contacto', 'verbose_name_plural': 'Formularios de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='flan',
            options={'verbose_name': 'Flan', 'verbose_name_plural': 'Productos (Flanes)'},
        ),
        migrations.AlterModelOptions(
            name='usuarioform',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Registro de Usuarios'},
        ),
    ]
